### PR TITLE
Add compatibility with Laravel 9

### PR DESCRIPTION
**Pull request by josecanhelp**
All tests are passing.

### CODE REVIEW

**Comment by butschster** [comment]
Hi @josecanhelp! Thank you! Could you please update readme?

**Comment by josecanhelp** [comment]
Sure thing. The Readme is still technically correct since it states that laravel 8+ is supported. Would you like it to explicitly state 8 and 9?

**Comment by butschster** [comment]
> Sure thing. The Readme is still technically correct since it states that laravel 8+ is supported. Would you like it to explicitly state 8 and 9?

yeah!

**Comment by josecanhelp** [comment]
@butschster Done. 🥳

**Pull request merged**
